# Generated by Django 3.2.9 on 2021-11-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20211105_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_number',
            field=models.IntegerField(db_index=True, verbose_name='Номер изображения'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
