# Generated by Django 3.2.9 on 2021-11-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20211105_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['number']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='img_number',
            new_name='number',
        ),
    ]
